export const steemTip = 'Tradeable tokens that may be transferred anywhere at anytime. Steem can be converted to Steem Power in a process called powering up.'
export const dollarTip = 'Tokens valuados aproximadamente en $1.00 de Steem.'
//export const powerTip = 'Influence tokens which give you more control over post payouts and allow you to earn on curation rewards.'
export const powerTip = 'Influence tokens which earn more power by holding long term. The more you hold the more you influence post rewards and earn for accurate voting.'
export const valueTip = 'La valuación estimada está basada en un promedio del precio de STEEM en USD durante 7 dias.'
export const powerTip2 = 'El Steem Power no es transferible y requiere 2 años y 104 pagos para convertirlo a STEEM.'
export const powerTip3 = 'El Steem Power convertido puede ser enviado a vos mismo o a otro usuario pero no se puede volver a transferir sin convertilos a STEEM nuevamente.'
